package com.aws.dynamodb.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.aws.dynamodb.converter.LocalDateTimeTypeConverter;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@NoArgsConstructor
@DynamoDBTable(tableName = "Article")
@Getter
@Setter
public class Article {

    @DynamoDBHashKey(attributeName = "idx")
    @DynamoDBAutoGeneratedKey
    private String idx;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "code-createDate-Index", attributeName = "createDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeTypeConverter.class)
    @DynamoDBAttribute
    private LocalDateTime createDate;

    @DynamoDBIndexHashKey(globalSecondaryIndexNames = "code-createDate-Index", attributeName = "code")
    @DynamoDBAttribute
    private String code;

    @DynamoDBAttribute(attributeName = "subject")
    private String subject;

    @DynamoDBAttribute(attributeName = "contents")
    private String contents;

    @DynamoDBAttribute(attributeName = "count")
    private int count;

    @Builder(toBuilder = true)
    public Article(String idx, LocalDateTime createDate, String code, String subject, String contents, int count) {
        this.idx = idx;
        this.createDate = createDate;
        this.code = code;
        this.subject = subject;
        this.contents = contents;
        this.count = count;
    }

    public void update(String subject, String contents){
        this.subject = subject;
        this.contents = contents;
    }

    public void initBeforeCreate(){
        this.createDate = LocalDateTime.now();
        this.count = 0;
        this.code = "temp";
    }
}
