package com.aws.dynamodb.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.aws.dynamodb.converter.LocalDateTimeTypeConverter;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Set;

@NoArgsConstructor
@DynamoDBTable(tableName = "Article")
@Getter
@Setter
public class Article {

    /**
     * 테이블 파티션 키
     */
    @DynamoDBHashKey(attributeName = "idx")
    @DynamoDBAutoGeneratedKey
    private String idx;

    /**
     * 정렬키(범위 속성)
     */
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "code-createDate-Index", attributeName = "createDate")
    @DynamoDBTypeConverted(converter = LocalDateTimeTypeConverter.class)
    @DynamoDBAttribute
    private LocalDateTime createDate;

    /**
     * global secondary index 파티션 키
     */
    @DynamoDBIndexHashKey(globalSecondaryIndexNames = "code-createDate-Index", attributeName = "code")
    @DynamoDBAttribute
    private String code;

    @DynamoDBAttribute(attributeName = "subject")
    private String subject;

    @DynamoDBAttribute(attributeName = "contents")
    private String contents;

    @DynamoDBAttribute(attributeName = "count")
    private int count;

    @DynamoDBAttribute
    private Set<String> data1;

    @DynamoDBAttribute
    private Map<String, String> data2;

    @Builder(toBuilder = true)
    public Article(String idx, LocalDateTime createDate, String code
            , String subject, String contents, int count
            , Set<String> data1, Map<String, String> data2) {

        this.idx = idx;
        this.createDate = createDate;
        this.code = code;
        this.subject = subject;
        this.contents = contents;
        this.count = count;
        this.data1 = data1;
        this.data2 = data2;
    }

    public void update(String subject, String contents){
        this.subject = subject;
        this.contents = contents;
    }

    public void initBeforeCreate(){
        this.createDate = LocalDateTime.now();
        this.count = 0;
        this.code = "temp";
    }
}
