aws:
  region:
  dynamo:
    endpoint: http://localhost:8000/
  access-key:
  secret-key:
  credential:
    profile: default

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
